# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180823_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
