# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180817_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='title',
        ),
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Skill'),
        ),
    ]
