# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180821_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Skill'),
        ),
    ]
