# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180828_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
