# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicant_req',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='time_line_description',
            field=models.TextField(default=''),
        ),
    ]
