# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180830_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
