# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='project',
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.Position'),
            preserve_default=False,
        ),
    ]
