# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180831_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
